/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Labels.Label_Info;

import Labels.Label_Inicio.Inicio;
import Labels.Label_Selecc_Pokemon.Reglas;
import Labels.Label_Selecc_Pokemon.Seleccion_Pokemon;

/**
 *
 * @author Usuario
 */
public class Informacion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informacion.class.getName());

    /**
     * Creates new form Seleccion
     */
    public Informacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btndevolver = new javax.swing.JButton();
        btnselecc = new javax.swing.JButton();
        btnReglas = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 248, 220));
        jPanel1.setForeground(new java.awt.Color(255, 102, 153));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Charmander", "Fuego", "Aire", "Agua",  new Integer(200),  new Integer(25),  new Integer(20),  new Integer(40),  new Integer(35)},
                {"Squirtle", "Agua", "Fuego", "Electro",  new Integer(175),  new Integer(40),  new Integer(20),  new Integer(55),  new Integer(38)},
                {"Pidgey", "Aire", "Tierra", "Electro",  new Integer(175),  new Integer(30),  new Integer(20),  new Integer(40),  new Integer(39)},
                {"Pikachu", "Electro", "Agua/aire", "Tierra",  new Integer(150),  new Integer(35),  new Integer(29),  new Integer(45),  new Integer(32)},
                {"Sandshrew", "Tierra", "Electro", "Agua",  new Integer(300),  new Integer(15),  new Integer(40),  new Integer(30),  new Integer(50)},
                {"Diglett", "Tierra", "Electro", "Agua",  new Integer(250),  new Integer(19),  new Integer(38),  new Integer(25),  new Integer(46)},
                {"Ponyta", "Fuego", "Aire", "Agua/tierra",  new Integer(225),  new Integer(30),  new Integer(25),  new Integer(39),  new Integer(33)},
                {"Psyduck", "Agua", "Fuego/tierra", "Electro",  new Integer(175),  new Integer(35),  new Integer(25),  new Integer(45),  new Integer(35)},
                {"Spearow", "Aire", "Neutro", "Electro",  new Integer(225),  new Integer(30),  new Integer(20),  new Integer(40),  new Integer(30)},
                {"Jolteon", "Electro", "Agua/aire", "Tierra",  new Integer(210),  new Integer(26),  new Integer(20),  new Integer(40),  new Integer(30)}
            },
            new String [] {
                "Pokemon", "Tipo", "Fuerte contra", "Debil contra", "Vida", "Ataque", "Defensa", "Ataque especial", "Defensa especial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Información de los pokemones");

        btndevolver.setText("Salir");
        btndevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndevolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndevolverMouseExited(evt);
            }
        });
        btndevolver.addActionListener(this::btndevolverActionPerformed);

        btnselecc.setText("Empezar");
        btnselecc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnseleccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnseleccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnseleccMouseExited(evt);
            }
        });
        btnselecc.addActionListener(this::btnseleccActionPerformed);

        btnReglas.setText("Reglas");
        btnReglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReglasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReglasMouseExited(evt);
            }
        });
        btnReglas.addActionListener(this::btnReglasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnselecc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnReglas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(btndevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 323, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnselecc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReglas, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btndevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndevolverActionPerformed

        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndevolverActionPerformed

    private void btnseleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccActionPerformed

        Seleccion_Pokemon seleccion_pokemon = new Seleccion_Pokemon();
        seleccion_pokemon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnseleccActionPerformed

    private void btnReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglasActionPerformed

        Reglas reglas = new Reglas();
        reglas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnReglasActionPerformed

    private void btnseleccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnseleccMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnseleccMouseClicked

    private void btnseleccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnseleccMouseEntered
                                         
    btnselecc.setBackground(new java.awt.Color(210, 195, 150));

        
    }//GEN-LAST:event_btnseleccMouseEntered

    private void btnseleccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnseleccMouseExited
    btnselecc.setBackground(new java.awt.Color(220, 220, 220));
    }//GEN-LAST:event_btnseleccMouseExited

    private void btnReglasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseEntered
        btnReglas.setBackground(new java.awt.Color(210, 195, 150));
    }//GEN-LAST:event_btnReglasMouseEntered

    private void btnReglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseExited
     btnReglas.setBackground(new java.awt.Color(220, 220, 220));
    }//GEN-LAST:event_btnReglasMouseExited

    private void btndevolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndevolverMouseEntered
       btndevolver.setBackground(new java.awt.Color(210, 195, 150));
    }//GEN-LAST:event_btndevolverMouseEntered

    private void btndevolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndevolverMouseExited
       btndevolver.setBackground(new java.awt.Color(220, 220, 220));
    }//GEN-LAST:event_btndevolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Informacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReglas;
    private javax.swing.JButton btndevolver;
    private javax.swing.JButton btnselecc;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
